### ISSUE TITLE
OverwriteModelError: Cannot overwrite `Elements` model once compiled

### ISSUE THREAD

**Issue by ravecat** [ravecat/mendeleev_api#23]
```bash
OverwriteModelError: Cannot overwrite `Elements` model once compiled.
    at new OverwriteModelError (/home/max/project/mendeleev_api/node_modules/mongoose/lib/error/overwriteModel.js:20:11)
    at Mongoose.model (/home/max/project/mendeleev_api/node_modules/mongoose/lib/index.js:453:13)
    at Object.<anonymous> (/home/max/project/mendeleev_api/src/models/elements/model.js:4:25)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (/home/max/project/mendeleev_api/node_modules/babel-register/lib/node.js:144:5)

```

**Comment by ravecat** [comment]
Fixed https://github.com/ravecat/mendeleev_api/pull/24
